### PR TITLE
get rid of returning operator

### PR DESCRIPTION
**Pull request by dmitry-a-l**
since rails 3.1 we have no `returning`

### CODE REVIEW

**Comment by karledurante** [comment]
Thanks for finding/fixing this.  I have to make another update to make, and then I'll publish a new version of the gem.  Holidays are coming up, hopefully happen in the next week or two.

**Comment by karledurante** [comment]
I've just pushed version 0.5.0 of the gem, which includes your changes.  Thanks again!

**Comment by dmitry-a-l** [comment]
ok, and asking to your question in README - yes, it works with Rails 3.1.x

**Comment by karledurante** [comment]
Thanks again, Dmitry.

**Pull request merged**
